### ISSUE TITLE
didn't work to me

### ISSUE THREAD

**Issue by TelmoGaspar** [angus-ai/angus-jumpingsumo#1]
I have done step by step but wen run ./wrapper.py  dint work! just appear some lines (not found)
(env)tg@ubuntu:/SumoSDK/angus-jumpingsumo$ ./wrapper.py
./wrapper.py: line 21: import: command not found
./wrapper.py: line 22: import: command not found
./wrapper.py: line 23: import: command not found
./wrapper.py: line 24: import: command not found
./wrapper.py: line 25: import: command not found
./wrapper.py: line 28: WIDTH: command not found
./wrapper.py: line 31: syntax error near unexpected token `('
./wrapper.py: line 31:`def img_generator(file_path):'

any idea about what can be?? One big possibility is the operator.. I'm very newbie on this!
thank you, regards Telmo

**Comment by yienyien** [comment]
Hi, 
    Thank you for your interest ! I need more details about your environment.
Could you execute and copy/paste the result:

```
python --version
```

Thank you.

**Comment by TelmoGaspar** [comment]
Hi, thank you..
the result is :Python 2.7.6

**Comment by yienyien** [comment]
Hmmmm,

could you try the following command and post me the result ?:

```
file /usr/bin/env
```

The wrapper script is in python, then, you can just run it with this command:

```
python ./wrapper.py
```

I try to make this script executable (with #!) but maybe it does not work on your system.

**Comment by TelmoGaspar** [comment]
Hello, TY
here it is
tg@ubuntu:/SumoSDK/angus-jumpingsumo$ file /usr/bin/env
/usr/bin/env: ELF 64-bit LSB  executable, x86-64, version 1 (SYSV), dynamically linked (uses shared libs), for GNU/Linux 2.6.24, BuildID[sha1]=1886e415fcd7ba45708e015105a7309c3c700f28, stripped
tg@ubuntu:/SumoSDK/angus-jumpingsumo$ 

python ./wrapper.py
Traceback (most recent call last):
  File "./wrapper.py", line 132, in <module>
    main()
  File "./wrapper.py", line 125, in main
    stderr=subprocess.STDOUT)
  File "/usr/lib/python2.7/subprocess.py", line 710, in **init**
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1327, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory

hope this helps
thank you again

**Comment by TelmoGaspar** [comment]
when i do the make.. it returns:

/angus-jumpingsumo$ sudo make
JumpingSumoInterface.c:57:28: fatal error: libARSAL/ARSAL.h: No such file or directory
 #include <libARSAL/ARSAL.h>
                            ^
compilation terminated.
make: *** [obj/JumpingSumoInterface.o] Error 1

**Comment by TelmoGaspar** [comment]
started from beginner and the result : 
 python ./wrapper.py
Traceback (most recent call last):
  File "./wrapper.py", line 25, in <module>
    import angus
ImportError: No module named angus
(env)tg@ubuntu:/SumoSDK/angus-jumpingsumo$ 

why cant import angus? wat is missing?

**Comment by TelmoGaspar** [comment]
if i do the run under the sudo (sudo python ./wrapper.py) returs this:

-- Jumping Sumo Interface --Traceback (most recent call last):
                                                                File "./wrapper.py", line 132, in <module>
                                      main()
                                              File "./wrapper.py", line 128, in main
                service = conn.services.get_service('face_detection', 1)
  File "/usr/local/lib/python2.7/dist-packages/angus/cloud.py", line 43, in get_service
                   description = self.list({'name': name})
                                                            File "/usr/local/lib/python2.7/dist-packages/angus/rest.py", line 122, in list
                                                                      r = self.conf.get(self.endpoint, params=filters)
                                                File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 473, in get
                                                                return self.request('GET', url, **kwargs)
                                   File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 447, in request
                                                       prep = self.prepare_request(req)
                 File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 378, in prepare_request
                                             hooks=merge_hooks(request.hooks, self.hooks),
                    File "/usr/local/lib/python2.7/dist-packages/requests/models.py", line 303, in prepare
                                      self.prepare_url(url, params)
                                                                     File "/usr/local/lib/python2.7/dist-packages/requests/models.py", line 360, in prepare_url
                   "Perhaps you meant http://{0}?".format(url))
                                                               requests.exceptions.MissingSchema: Invalid URL u'None//services': No schema supplied. Perhaps you meant http://None//services?
                                             tg@ubuntu:/SumoSDK/angus-jumpingsumo$

**Comment by yienyien** [comment]
Hi, sorry for the delay, we just build our own startup (Angus.ai) and this is a lot of work !

My documentation (README) is very light, and many steps are omitted. I will update it with more detailed steps and you could retry again.
